### ISSUE TITLE
What's printing O(n) 'get: {{url}}'?

### ISSUE THREAD

**Issue by steakknife** [rubygems/rubygems-mirror#44]
~~Grepping the various codebases, it's unclear where it's happening, i.e., rubygems, rubygems-mirror or net/http/persistent.  It's really noisy even with `gem mirror --silent --no-verbose` and slows things down with potentially around a million, repetitious lines.  The periods are `Gem.configuration.verbose`, that's simple enough to silence with `--no-verbose`.  Shell redirection while seemingly a quick fix, doesn't address the issue because `--no-verbose --silent` should be really quiet (errors only), which should be the default anyhow per [Unix Philosophy](https://en.wikipedia.org/wiki/Unix_philosophy).  Diffs welcomed/greatly appreciated.~~

``` yaml
# .gemrc

---
gem: --no-document
```

``` yaml
# .gem/.mirrorc

---
- from: {{redacted}}
  to: {{redacted}}
  parallelism: 50
  retries: 3
  delete: false
  skiperror: true
```
