### ISSUE TITLE
Update README to use HTTPS to link to rubygems.org

### ISSUE THREAD

**Issue by s2k** [rubygems/rubygems-mirror#81]
I suggest to update the README to use https instead of http: 

```yaml
---
- from: https://rubygems.org
  to: /data/rubygems
  parallelism: 10
  retries: 3
  delete: false
  skiperror: true
  hashdir: false
```

While technically not needed (since http://rubygem.org is redirected to https), using HTTPS throughout seems like a good idea.
